Rename private to local
WICG/local-network-access pull request #97
Opened 2023-01-18 18:14 UTC by johnathan79717

Fixes #91

2023-01-19 04:36 UTC, yoavweiss commented
Hey @johnathan79717 - can you join the WICG to appease the IPR bots? :)

2023-01-20 10:36 UTC, johnathan79717 commented
Ah right.  I requested to join WICG just now.

I have kept the header names the same until we decide what to do with it.  I'll probably need to modify the explainers if we're gonna go through with this.  Did I miss anything else?

2023-01-20 11:18 UTC, annevk commented
Please file explicit follow-up issues for things that are not renamed since you plan on closing the initial issue once this lands.

2023-01-20 11:27 UTC, johnathan79717 commented
> Please file explicit follow-up issues for things that are not renamed since you plan on closing the initial issue once this lands.

Good point.  I removed the keyword in the description so it should not close the initial issue now.

2023-02-21 16:20 UTC, johnathan79717 commented
Reopening this PR since renaming is back on the table.

2023-02-23 09:19 UTC, letitz commented
Let me know when this is ready for review.

2023-02-23 10:30 UTC, johnathan79717 commented
> Let me know when this is ready for review.

It is ready for review. 😄

2023-02-23 10:35 UTC, letitz commented
Perfect! I shall start reviewing then :)

2023-02-23 14:04 UTC, letitz requested changes
Looks good! I think we also want to update the base `explainer.md` file, right?

2023-02-24 11:23 UTC, johnathan79717 commented on README.md
Done

2023-02-24 11:23 UTC, johnathan79717 commented on HOWTO.md
>  1. `--enable-features=PrivateNetworkAccessSendPreflights`
Done

2023-02-24 12:56 UTC, letitz requested changes
Thanks very much! One last suggestion and we can merge.

2023-02-24 12:56 UTC, letitz commented on README.md
> +*Local Network Access*.
```suggestion
*Local Network Access*. It was also initially known as *CORS-RFC1918*.
```

2023-02-24 14:17 UTC, johnathan79717 commented on README.md
> +*Local Network Access*.
Done

2023-02-24 14:34 UTC, merged